# Generated by Django 3.0.7 on 2020-07-03 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_restapi.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='book_id',
            field=models.IntegerField(),
        ),
    ]
